export const CHOOSE_COLOR = 'CHOOSE_COLOR';
export const CHOOSE_MIXED_COLOR = 'CHOOSE_MIXED_COLOR';
export const ADD_COLOR = 'ADD_COLOR';
export const TOGGLE_PICKER = 'TOGGLE_PICKER';
export const DELETE_COLOR = 'DELETE_COLOR';
export const SELECT_ALL = 'SELECT_ALL';
export const MODIFY_COLOR = 'MODIFY_COLOR';
export const CHOOSE_MODIFIED_COLOR = 'CHOOSE_MODIFIED_COLOR';
export const MODIFY_COLOR_ADD = 'MODIFY_COLOR_ADD';

